name: CI

on:
  push:
  pull_request:

jobs:

  check-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup rust
      uses: dtolnay/rust-toolchain@stable
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check formatting with rustfmt
      run: cargo fmt -- --check

  check-clippy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup rust
      uses: dtolnay/rust-toolchain@stable
    - name: Install rustfmt
      run: rustup component add clippy
    - name: Check for clippy warnings
      run: cargo clippy --all-targets --all-features -- -D warnings -W clippy::cargo
