name: Release

on:
  push:
    tags:
      - '[0-9]+.*'

jobs:
  build-and-upload-linux-brew-binaries:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: TARGET=x86_64-unknown-linux-gnu ./build-zip.sh
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: linux-x86_64-binary
        path: rust-gpu-compiler-x86_64-unknown-linux-gnu.zip

  build-and-upload-mac-brew-binaries:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - run: rustup target add aarch64-apple-darwin
    - run: TARGET=aarch64-apple-darwin ./build-zip.sh
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: mac-aarch64-binary
        path: rust-gpu-compiler-aarch64-apple-darwin.zip

  github-release:
    needs: [build-and-upload-linux-brew-binaries, build-and-upload-mac-brew-binaries]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: mac-aarch64-binary
      - uses: actions/download-artifact@v4
        with:
          name: linux-x86_64-binary
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            rust-gpu-compiler-aarch64-apple-darwin.zip
            rust-gpu-compiler-x86_64-unknown-linux-gnu.zip
