name: Release

on:
  push:
    tags:
      - '[0-9]+.*'

jobs:
  build-and-upload-linux-brew-binaries:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: TARGET=x86_64-unknown-linux-gnu ./build-zip.sh
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: linux-x86_64-binary
        path: rust-gpu-driver-x86_64-unknown-linux-gnu.zip

  build-and-upload-mac-brew-binaries:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - run: rustup target add aarch64-apple-darwin
    - run: TARGET=aarch64-apple-darwin ./build-zip.sh
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: mac-aarch64-binary
        path: rust-gpu-driver-aarch64-apple-darwin.zip

  github-release:
    needs: [build-and-upload-linux-brew-binaries, build-and-upload-mac-brew-binaries]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: mac-aarch64-binary
      - uses: actions/download-artifact@v4
        with:
          name: linux-x86_64-binary
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            rust-gpu-driver-aarch64-apple-darwin.zip
            rust-gpu-driver-x86_64-unknown-linux-gnu.zip

  publish-homebrew:
    runs-on: ubuntu-latest
    needs: [github-release]
    steps:
    - name: Check out source code
      uses: actions/checkout@v4
    - run: |
        NEW_VERSION=$(./.github/workflows/current-version)
        curl -X POST -H "Authorization: Bearer ${{ secrets.HOMEBREW_TAP_GITHUB_ACCESS_TOKEN }} " -H "Accept:application/vnd.github" "https://api.github.com/repos/fornwall/homebrew-tap/actions/workflows/publish.yml/dispatches" -d "{\"ref\":\"main\", \"inputs\":{\"formula\":\"rust-gpu\",\"version\":\"$NEW_VERSION\"}}"
